baseURL = "https://illallangi.com"
languageCode = "en-au"
defaultContentLanguage = "en"
title = "illallangi.com"
theme = "papercss-hugo-theme"
googleAnalytics = "UA-123456789-1"
disqusShortname = "yourdiscussshortname"

[privacy]
  [privacy.disqus]
    disable = true

[taxonomies]
  category = "category"

[permalinks]
  posts = "/:year/:month/:day/:title/"

[imaging]
  quality = 99

[params]
  homeMetaContent = "Just another vanity domain"
  dateFormat = "RFC3339"

[menu]
  [[menu.nav]]
    name = "Blog"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Categories"
    url = "/category/"
    weight = 2
  [[menu.nav]]
    name = "Source"
    url = "https://github.com/illallangi/illallangi.com"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 4
